server.port=8080

spring.liquibase.url=jdbc:mysql://localhost:3306/diamond_shop_vip?useSSL=true
spring.liquibase.user=root
spring.liquibase.password=
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml,classpath:db/changelog/db.changelog-product.xml,classpath:db/changelog/db.changelog-users.xml

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

app.jwt.secret=BdvsvdkD9487j527G8545hnv8r38583

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope[0]=email
spring.security.oauth2.client.registration.google.scope[1]=profile

vnpay.tmnCode=VLZVILA6
vnpay.hashSecret=J6T41TYMICTNNKEE6T1U6B23UWE5J9CQ
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnurl=http://localhost:8080/vn-pay-callback
vnpay.version=2.1.0
vnpay.command=pay
vnpay.orderType=other









